// دیتابیس فرضی محصولات — در آینده این باید از یک دیتابیس واقعی (مثل Postgres) بیاید.
// فعلاً برای شروع ساده، همینجا به‌صورت یک آرایه نگه داشته می‌شود.

export const PRODUCTS = [
  { id: "p-gaming-1", name: "ROG Strix G16", price: 68000000, category: "laptop", description: "لپ‌تاپ گیمینگ قدرتمند با خنک‌کنندگی عالی، مناسب گیم‌های سنگین و برنامه‌نویسی همزمان.", specifications: { cpu: "Intel Core i7-13650HX", gpu: "RTX 4060 8GB", ram: "16GB DDR5", storage: "1TB SSD", screen: "16 اینچ 165Hz" }, use_cases: ["gaming", "programming"], stock: 4 },
  { id: "p-gaming-2", name: "Legion Pro 5", price: 71500000, category: "laptop", description: "مناسب گیمرهایی که برنامه‌نویسی سنگین هم انجام می‌دهند.", specifications: { cpu: "AMD Ryzen 7 7745HX", gpu: "RTX 4070 8GB", ram: "16GB DDR5", storage: "1TB SSD", screen: "16 اینچ 165Hz" }, use_cases: ["gaming", "programming"], stock: 2 },
  { id: "p-gaming-3", name: "Nitro V15", price: 52000000, category: "laptop", description: "گزینه اقتصادی برای گیم‌های متوسط و برنامه‌نویسی روزمره.", specifications: { cpu: "Intel Core i5-13420H", gpu: "RTX 4050 6GB", ram: "16GB DDR5", storage: "512GB SSD", screen: "15.6 اینچ 144Hz" }, use_cases: ["gaming", "programming", "general"], stock: 7 },
  { id: "p-gaming-4", name: "TUF Gaming A15", price: 47000000, category: "laptop", description: "مقاوم و بادوام، برای گیمینگ سبک تا متوسط.", specifications: { cpu: "AMD Ryzen 5 7535HS", gpu: "RTX 3050 6GB", ram: "8GB DDR5", storage: "512GB SSD", screen: "15.6 اینچ 144Hz" }, use_cases: ["gaming"], stock: 6 },
  { id: "p-gaming-5", name: "Predator Helios 18", price: 135000000, category: "laptop", description: "تاپ‌رنج مطلق، برای گیمینگ 4K و رندر سنگین.", specifications: { cpu: "Intel Core i9-14900HX", gpu: "RTX 4090 16GB", ram: "32GB DDR5", storage: "2TB SSD", screen: "18 اینچ 240Hz" }, use_cases: ["gaming", "design", "programming"], stock: 1 },
  { id: "p-ultra-1", name: "UltraBook Air 14", price: 58000000, category: "laptop", description: "سبک و کم‌حجم، مناسب برنامه‌نویسی و کار روزمره، باتری طولانی.", specifications: { cpu: "Intel Core i7-1355U", gpu: "Intel Iris Xe", ram: "16GB LPDDR5", storage: "512GB SSD", screen: "14 اینچ 2.2K" }, use_cases: ["programming", "office", "general"], stock: 9 },
  { id: "p-ultra-2", name: "ZenBook Pro 14", price: 64500000, category: "laptop", description: "صفحه‌نمایش OLED با کیفیت بالا، مناسب برنامه‌نویسی و طراحی سبک.", specifications: { cpu: "Intel Core i7-13700H", gpu: "RTX 4050 6GB", ram: "16GB DDR5", storage: "1TB SSD", screen: "14.5 اینچ OLED 2.8K" }, use_cases: ["programming", "design"], stock: 3 },
  { id: "p-ultra-3", name: "ThinkBook 14+", price: 49000000, category: "laptop", description: "مناسب برنامه‌نویسان و کارهای اداری سنگین.", specifications: { cpu: "AMD Ryzen 7 7840HS", gpu: "Radeon 780M", ram: "16GB DDR5", storage: "512GB SSD", screen: "14 اینچ 2.8K" }, use_cases: ["programming", "office"], stock: 8 },
  { id: "p-work-1", name: "WorkStation P16", price: 98000000, category: "laptop", description: "ایستگاه کاری برای برنامه‌نویسی سنگین و ماشین مجازی.", specifications: { cpu: "Intel Core i9-13980HX", gpu: "RTX 4080 12GB", ram: "32GB DDR5", storage: "2TB SSD", screen: "16 اینچ 4K" }, use_cases: ["programming", "design"], stock: 2 },
  { id: "p-work-2", name: "Precision Dev 15", price: 83000000, category: "laptop", description: "برای توسعه‌دهندگانی که با کانتینر و چند محیط مجازی کار می‌کنند.", specifications: { cpu: "Intel Core i7-13800H", gpu: "RTX 4060 8GB", ram: "32GB DDR5", storage: "1TB SSD", screen: "15.6 اینچ QHD" }, use_cases: ["programming"], stock: 4 },
  { id: "p-budget-1", name: "IdeaPad Slim 3", price: 29500000, category: "laptop", description: "اقتصادی برای کارهای عمومی، اینترنت، آفیس.", specifications: { cpu: "AMD Ryzen 5 7520U", gpu: "Radeon Graphics یکپارچه", ram: "8GB DDR5", storage: "512GB SSD", screen: "15.6 اینچ FHD" }, use_cases: ["office", "general"], stock: 12 },
  { id: "p-budget-2", name: "Aspire Lite", price: 26000000, category: "laptop", description: "مناسب دانش‌آموز و کارهای سبک.", specifications: { cpu: "Intel Core i3-1215U", gpu: "Intel UHD", ram: "8GB DDR4", storage: "256GB SSD", screen: "15.6 اینچ FHD" }, use_cases: ["office", "general"], stock: 10 },
  { id: "p-design-1", name: "Creator Z16", price: 92000000, category: "laptop", description: "مانیتور رنگ‌دقیق، مناسب طراحی گرافیک؛ توان کافی برای گیم و کد هم دارد.", specifications: { cpu: "Intel Core i9-13900H", gpu: "RTX 4070 8GB", ram: "32GB DDR5", storage: "1TB SSD", screen: "16 اینچ 4K+ رنگ‌دقیق" }, use_cases: ["design", "gaming", "programming"], stock: 2 },
  { id: "p-design-2", name: "Studio Book 16", price: 87500000, category: "laptop", description: "برای موشن‌گرافیک و رندر سبک، هم‌زمان مناسب گیم.", specifications: { cpu: "AMD Ryzen 9 7940HS", gpu: "RTX 4070 8GB", ram: "32GB DDR5", storage: "1TB SSD", screen: "16 اینچ QHD+" }, use_cases: ["design", "gaming"], stock: 3 },
  { id: "p-office-1", name: "Latitude Basic 14", price: 34000000, category: "laptop", description: "مناسب محیط اداری، سبک و قابل‌حمل.", specifications: { cpu: "Intel Core i5-1335U", gpu: "Intel Iris Xe", ram: "8GB DDR5", storage: "512GB SSD", screen: "14 اینچ FHD" }, use_cases: ["office"], stock: 11 },
  { id: "p-office-2", name: "EliteBook Compact", price: 41000000, category: "laptop", description: "مقاوم، امنیت بالا، مناسب کسب‌وکارهای کوچک.", specifications: { cpu: "Intel Core i5-1345U", gpu: "Intel Iris Xe", ram: "16GB DDR5", storage: "512GB SSD", screen: "14 اینچ FHD" }, use_cases: ["office", "general"], stock: 9 },
  { id: "p-gaming-6", name: "Blade Compact 14", price: 99500000, category: "laptop", description: "گیمینگ حرفه‌ای در بدنه‌ی جمع‌وجور.", specifications: { cpu: "Intel Core i9-13900H", gpu: "RTX 4070 8GB", ram: "32GB DDR5", storage: "1TB SSD", screen: "14 اینچ QHD+ 240Hz" }, use_cases: ["gaming", "programming"], stock: 2 },
  { id: "p-mid-1", name: "Swift Balance 15", price: 44500000, category: "laptop", description: "تعادل خوب بین قیمت و کارایی برای برنامه‌نویسی و گیم‌های متوسط.", specifications: { cpu: "AMD Ryzen 5 7640HS", gpu: "RTX 3050 Ti 4GB", ram: "16GB DDR5", storage: "512GB SSD", screen: "15.6 اینچ 144Hz" }, use_cases: ["gaming", "programming", "general"], stock: 6 },
  { id: "p-mid-2", name: "Victus Value 16", price: 57000000, category: "laptop", description: "ترکیب مناسب گرافیک و پردازنده برای بودجه متوسط.", specifications: { cpu: "Intel Core i5-13500H", gpu: "RTX 4050 6GB", ram: "16GB DDR5", storage: "512GB SSD", screen: "16.1 اینچ 144Hz" }, use_cases: ["gaming", "programming"], stock: 5 },
  { id: "p-mid-3", name: "Katana Value 15", price: 65500000, category: "laptop", description: "گزینه محبوب برای بودجه حدود ۷۰ میلیون، گیم و برنامه‌نویسی هر دو.", specifications: { cpu: "Intel Core i7-13620H", gpu: "RTX 4060 8GB", ram: "16GB DDR5", storage: "512GB SSD", screen: "15.6 اینچ 144Hz" }, use_cases: ["gaming", "programming"], stock: 6 },
  { id: "p-mid-4", name: "Loq Balanced 15", price: 69500000, category: "laptop", description: "مناسب گیم و برنامه‌نویسی با بودجه حدود ۷۰ میلیون.", specifications: { cpu: "Intel Core i7-13650HX", gpu: "RTX 4060 8GB", ram: "16GB DDR5 (قابل ارتقا)", storage: "1TB SSD", screen: "15.6 اینچ 144Hz" }, use_cases: ["gaming", "programming"], stock: 5 },
  { id: "p-mini-1", name: "GO Slim 13", price: 38500000, category: "laptop", description: "جمع‌وجور برای دانشجو، مناسب برنامه‌نویسی سبک.", specifications: { cpu: "Intel Core i5-1335U", gpu: "Intel Iris Xe", ram: "16GB DDR5", storage: "512GB SSD", screen: "13.3 اینچ FHD" }, use_cases: ["programming", "office", "general"], stock: 8 },
  { id: "p-mini-2", name: "Air Compact 13", price: 35000000, category: "laptop", description: "سبک‌ترین گزینه فروشگاه، مناسب حمل روزانه.", specifications: { cpu: "Intel Core i3-1315U", gpu: "Intel UHD", ram: "8GB DDR5", storage: "256GB SSD", screen: "13.3 اینچ FHD" }, use_cases: ["general", "office"], stock: 10 },
];

export function findById(id) {
  return PRODUCTS.find((p) => p.id === id);
}
